name: Build_phicomm_k2g

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "选择源码分支"
        required: false
        default: "lede-master"
        type: choice
        options:
          - lede-master
          - immortalwrt-master  
          
      log_switch:
        description: "Compile log switch"
        required: false
        default: "false"
        type: boolean
        options:
          - true
          - false
  
env:
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 清理磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true

    - name: 初始化环境
      run: |
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/LeeHe-gif/depend_ubuntu2204_openwrt/main/depend_ubuntu2204_openwrt)
        sudo timedatectl set-timezone "${TZ}"
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: 克隆源码
      run: |
        case "${{ inputs.source_branch }}" in
            "lede-master")
                REPO_URL="https://github.com/coolsnowwolf/lede"
                REPO_BRANCH="master"
                ;;
            "immortalwrt-master")
                REPO_URL="https://github.com/immortalwrt/immortalwrt"
                REPO_BRANCH="master"
                ;;
            *)
                echo "::error::未知的源码仓库"
                exit 1
                ;;
        esac
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo 'src-git modem https://github.com/FUjr/modem_feeds.git;main' >> feeds.conf.default

    - name: 配置缓存目录
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt/{dl,staging_dir,build_dir}
        ln -sfn /mnt/openwrt/dl openwrt/dl
        ln -sfn /mnt/openwrt/staging_dir openwrt/staging_dir
        ln -sfn /mnt/openwrt/build_dir openwrt/build_dir
        
    - name: 更新安装 feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        sed -i 's/PKG_VERSION:=0.46.033/PKG_VERSION:=0.46.079/' feeds/luci/applications/luci-app-openclash/Makefile
        ./scripts/feeds install -a
        ./scripts/feeds install -a -f -p modem

    - name: 自定义配置
      run: |
        if [[ "${{ inputs.source_branch }}" == *"lede"* ]]; then
          chmod +x ./customize.sh && ./customize.sh
          CONFIG_FILE="config/lede-phicomm-k2g.config"
        else
          chmod +x ./imm-customize.sh && ./imm-customize.sh   
          CONFIG_FILE="config/imm_phicomm_k2g.config"
        fi
        [[ -d "files" ]] && cp -r files openwrt/files
        cp -fv "${CONFIG_FILE}" openwrt/.config
        cd openwrt && make defconfig
        
    - name: 下载软件包
      run: |
        cd openwrt/
        make download -j$(nproc) || { echo "::error::下载失败"; exit 1; }
        find dl -size -1024c -delete

    - name: 编译固件
      id: compile
      run: |
        cd openwrt/
        if [[ "${{ inputs.log_switch }}" == "true" ]]; then
            make -j1 V=s
        else
            make -j$(nproc)
        fi
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 整理固件文件
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/* || { echo "::error::固件目录不存在"; exit 1; }
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 上传固件产物
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}/*
        retention-days: 3

    - name: 准备发布信息
      id: release
      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        cat <<EOF > release.txt
        🚀 Phicomm K2G 固件
        ------------------
        源码: ${{ inputs.source_branch == 'lede-master' && 'coolsnowwolf/lede' || 'immortalwrt/immortalwrt' }}
        分支: $REPO_BRANCH
        时间: $(date +"%Y-%m-%d %H:%M")
        EOF

    - name: 创建发布版本
      uses: softprops/action-gh-release@v1
      if: steps.organize.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: 清理旧工作流
      if: always()
      uses: LeeHe-gif/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
        token: ${{ secrets.GITHUB_TOKEN }}
