name: Build_X86

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      log_switch:
        description: "Compile log switch"
        required: false
        default: "false"
        type: boolean
        options:
          - true
          - false
          
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  CONFIG_FILE: "config/X86.config"
  REPO_BRANCH: master
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: 清理磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true

    - name: 初始化环境
      run: |
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/LeeHe-gif/depend_ubuntu2204_openwrt/main/depend_ubuntu2204_openwrt)
        sudo timedatectl set-timezone "${TZ}"
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: 克隆源码
      id: clone
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        git clone --depth 1 https://github.com/vernesong/OpenClash.git OpenClash
        cd openwrt
        sed -i 's/^#src-git helloworld/src-git helloworld/' feeds.conf.default
        echo 'src-git istore https://github.com/linkease/istore;main' >> feeds.conf.default
        echo 'src-git nas https://github.com/linkease/nas-packages.git;master' >> feeds.conf.default
        echo 'src-git nas_luci https://github.com/linkease/nas-packages-luci.git;main' >> feeds.conf.default
        echo "src-git fancontrol https://github.com/LeeHe-gif/luci-app-fancontrol.git" >> "feeds.conf.default"
        git clone https://github.com/LeeHe-gif/luci-app-webpanel.git package/webpanel/luci-app-webpanel
        git clone https://github.com/tty228/luci-app-wechatpush.git package/wechatpush/luci-app-wechatpush
        sed -i 's/^#src-git qmodem/src-git qmodem/' feeds.conf.default
        echo "HASH=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV
        echo "DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV

    - name: 配置缓存目录
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt/{dl,staging_dir,build_dir}
        ln -sfn /mnt/openwrt/dl openwrt/dl
        ln -sfn /mnt/openwrt/staging_dir openwrt/staging_dir
        ln -sfn /mnt/openwrt/build_dir openwrt/build_dir

    - name: 缓存工具链
      uses: actions/cache@v3
      id: toolchain-cache
      with:
        path: |
          openwrt/staging_dir
          openwrt/build_dir
          openwrt/.ccache
        key: ${{ runner.os }}-toolchain-${{ env.HASH }}-${{ env.DATE }}
        restore-keys: |
          ${{ runner.os }}-toolchain-${{ env.HASH }}-
          ${{ runner.os }}-toolchain-

    - name: 刷新缓存时间戳
      if: steps.toolchain-cache.outputs.cache-hit == 'true'
      run: |
        find openwrt/staging_dir -type f -name ".stamp_*" -exec touch {} +
        find openwrt/build_dir -type f -name ".stamp_*" -exec touch {} +

    - name: 更新安装 feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        rm -rf feeds/luci/applications/luci-app-openclash
        cp -r ../OpenClash/luci-app-openclash feeds/luci/applications/
        ./scripts/feeds install -a -f

    - name: 自定义配置
      run: |
        chmod +x ./customize.sh && ./customize.sh
        [[ -d "files" ]] && cp -r files openwrt/files
        cp -fv "${CONFIG_FILE}" openwrt/.config
        cd openwrt && make defconfig
        
    - name: 下载软件包
      run: |
        cd openwrt/
        make download -j$(nproc) || { echo "::error::下载失败"; exit 1; }
        find dl -size -1024c -delete

    - name: 编译固件
      id : compile
      run: |
        cd openwrt/
        if [[ "${{ inputs.log_switch }}" == "true" ]]; then
            make -j1 V=s
        else
            make -j$(nproc)
        fi
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: 整理固件文件
      id: organize
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      run: |
        cd openwrt/bin/targets/*/* || { echo "::error::固件目录不存在"; exit 1; }
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: 上传固件文件
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}/*

    - name: 准备发布信息
      id : release
      if : steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true'
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        cat <<EOF > release.txt
        🚀 OpenWrt X86 固件
        ------------------
        源码: $REPO_URL
        分支: $REPO_BRANCH
        时间: $(date +"%Y-%m-%d %H:%M")
        特性: 包含OpenClash等常用插件
        EOF

    - name: 创建发布版本
      uses: softprops/action-gh-release@v1
      if: steps.organize.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: 清理旧工作流
      if: always()
      uses: LeeHe-gif/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
        token: ${{ secrets.GITHUB_TOKEN }}
